# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jiaye Chen"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jiaye.a.chen@yale.edu"

resume_header_intro: "<p>Hello and welcome to my personal page! 
<br><br>
I’m currently immersed in my Master of Science studies at Yale University, focusing on the dynamic field of health informatics. My academic journey began at the University of California, Davis, where I double majored in Managerial Economics and Statistics, honing a unique blend of business acumen and analytical prowess.
<br><br>
With a keen interest in the transformative power of data, I’ve developed a passion for data science and analytics. This platform serves as a window into my academic pursuits and the intriguing intersections of health informatics, statistics, and managerial economics.
<br><br>
Curious to see the real-world applications of my data-driven endeavors? Head over to the <b>Projects</b> section to explore a collection of data projects that showcase my hands-on experience and the exciting challenges I’ve tackled. Join me on this exploration of data science, where each project tells a unique story of analysis, insights, and innovation.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL

resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
